-- Renachem POS - Supabase PostgreSQL Schema Migration

-- USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('Admin','Pharmacist','Cashier')),
    is_active INTEGER DEFAULT 1,
    is_temp_password INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- LOGIN ATTEMPTS
CREATE TABLE IF NOT EXISTS public.login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMP WITH TIME ZONE
);

-- MEDICINES / INVENTORY
CREATE TABLE IF NOT EXISTS public.medicines (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    supplier TEXT,
    batch TEXT,
    expiry TEXT,
    stock INTEGER DEFAULT 0,
    reorder_level INTEGER DEFAULT 10,
    price REAL DEFAULT 0,
    cost_price REAL DEFAULT 0,
    barcode TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PATIENTS
CREATE TABLE IF NOT EXISTS public.patients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    age TEXT,
    gender TEXT,
    diagnosis TEXT,
    prescriptions TEXT,
    history TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CUSTOMERS
CREATE TABLE IF NOT EXISTS public.customers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    prescriptions TEXT,
    history TEXT
);

-- SUPPLIERS
CREATE TABLE IF NOT EXISTS public.suppliers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    contact TEXT,
    items TEXT
);

-- PURCHASES
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    med_name TEXT,
    batch TEXT,
    qty INTEGER,
    date TEXT,
    supplier TEXT,
    unit_price REAL,
    total_cost REAL
);

-- SALES
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    date_time TEXT,
    items_json TEXT,
    total REAL,
    payment_mode TEXT,
    customer_name TEXT,
    mpesa_code TEXT
);

-- AUDIT LOG
CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username TEXT,
    action TEXT,
    module TEXT,
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    row_hash TEXT
);

-- SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- CREDITS
CREATE TABLE IF NOT EXISTS public.credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT,
    customer_name TEXT NOT NULL,
    total_amount REAL NOT NULL,
    amount_paid REAL DEFAULT 0,
    balance REAL NOT NULL,
    status TEXT CHECK(status IN ('Pending', 'Partial', 'Paid')) DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_payment_date TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY(sale_id) REFERENCES public.sales(id)
);

-- CREDIT PAYMENTS
CREATE TABLE IF NOT EXISTS public.credit_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id BIGINT,
    amount REAL NOT NULL,
    payment_mode TEXT NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    received_by TEXT,
    FOREIGN KEY(credit_id) REFERENCES public.credits(id)
);

-- SECURITY POLICIES (Row Level Security - RLS)
-- For now, we will enable RLS but allow anon access for migration purposes.
-- IN PRODUCTION, these policies must be locked down to authenticated users only.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read access" ON public.medicines FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read access" ON public.sales FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read access" ON public.credits FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read access" ON public.credit_payments FOR SELECT USING (true);
